MLBASICEPATH="/mdfsvc/ML_BASIC"
PYTHONPATH=$PYTHONPATH:$MLBASICEPATH

export PYTHONPATH

nohup python3 ${MLBASICEPATH}/20240325_PBL_PRO_1/pbl_pro_1.py > ${MLBASICEPATH}/20240325_PBL_PRO_1/log/nohup.out &
